// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

/*
Package chat is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	UserRequest
	ChatMsg
	RoomMsg
*/
package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserRequest_UserRequestType int32

const (
	UserRequest_USER_LOGIN UserRequest_UserRequestType = 0
	UserRequest_USER_CHAT  UserRequest_UserRequestType = 1
)

var UserRequest_UserRequestType_name = map[int32]string{
	0: "USER_LOGIN",
	1: "USER_CHAT",
}
var UserRequest_UserRequestType_value = map[string]int32{
	"USER_LOGIN": 0,
	"USER_CHAT":  1,
}

func (x UserRequest_UserRequestType) String() string {
	return proto.EnumName(UserRequest_UserRequestType_name, int32(x))
}
func (UserRequest_UserRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type RoomMsg_RoomMsgType int32

const (
	RoomMsg_USER_JOIN  RoomMsg_RoomMsgType = 0
	RoomMsg_USER_LEAVE RoomMsg_RoomMsgType = 1
	RoomMsg_USER_CHAT  RoomMsg_RoomMsgType = 2
)

var RoomMsg_RoomMsgType_name = map[int32]string{
	0: "USER_JOIN",
	1: "USER_LEAVE",
	2: "USER_CHAT",
}
var RoomMsg_RoomMsgType_value = map[string]int32{
	"USER_JOIN":  0,
	"USER_LEAVE": 1,
	"USER_CHAT":  2,
}

func (x RoomMsg_RoomMsgType) String() string {
	return proto.EnumName(RoomMsg_RoomMsgType_name, int32(x))
}
func (RoomMsg_RoomMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type UserRequest struct {
	ReqType UserRequest_UserRequestType `protobuf:"varint,1,opt,name=req_type,json=reqType,enum=UserRequest_UserRequestType" json:"req_type,omitempty"`
	// Types that are valid to be assigned to UserRequestValues:
	//	*UserRequest_Name
	//	*UserRequest_Chat
	UserRequestValues isUserRequest_UserRequestValues `protobuf_oneof:"user_request_values"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isUserRequest_UserRequestValues interface {
	isUserRequest_UserRequestValues()
}

type UserRequest_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,oneof"`
}
type UserRequest_Chat struct {
	Chat string `protobuf:"bytes,3,opt,name=chat,oneof"`
}

func (*UserRequest_Name) isUserRequest_UserRequestValues() {}
func (*UserRequest_Chat) isUserRequest_UserRequestValues() {}

func (m *UserRequest) GetUserRequestValues() isUserRequest_UserRequestValues {
	if m != nil {
		return m.UserRequestValues
	}
	return nil
}

func (m *UserRequest) GetReqType() UserRequest_UserRequestType {
	if m != nil {
		return m.ReqType
	}
	return UserRequest_USER_LOGIN
}

func (m *UserRequest) GetName() string {
	if x, ok := m.GetUserRequestValues().(*UserRequest_Name); ok {
		return x.Name
	}
	return ""
}

func (m *UserRequest) GetChat() string {
	if x, ok := m.GetUserRequestValues().(*UserRequest_Chat); ok {
		return x.Chat
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UserRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UserRequest_OneofMarshaler, _UserRequest_OneofUnmarshaler, _UserRequest_OneofSizer, []interface{}{
		(*UserRequest_Name)(nil),
		(*UserRequest_Chat)(nil),
	}
}

func _UserRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UserRequest)
	// user_request_values
	switch x := m.UserRequestValues.(type) {
	case *UserRequest_Name:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Name)
	case *UserRequest_Chat:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Chat)
	case nil:
	default:
		return fmt.Errorf("UserRequest.UserRequestValues has unexpected type %T", x)
	}
	return nil
}

func _UserRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UserRequest)
	switch tag {
	case 2: // user_request_values.name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.UserRequestValues = &UserRequest_Name{x}
		return true, err
	case 3: // user_request_values.chat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.UserRequestValues = &UserRequest_Chat{x}
		return true, err
	default:
		return false, nil
	}
}

func _UserRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UserRequest)
	// user_request_values
	switch x := m.UserRequestValues.(type) {
	case *UserRequest_Name:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Name)))
		n += len(x.Name)
	case *UserRequest_Chat:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Chat)))
		n += len(x.Chat)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ChatMsg struct {
	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *ChatMsg) Reset()                    { *m = ChatMsg{} }
func (m *ChatMsg) String() string            { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()               {}
func (*ChatMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChatMsg) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChatMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RoomMsg struct {
	MsgType RoomMsg_RoomMsgType `protobuf:"varint,1,opt,name=msg_type,json=msgType,enum=RoomMsg_RoomMsgType" json:"msg_type,omitempty"`
	UserId  int64               `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	// Types that are valid to be assigned to RoomMsgValues:
	//	*RoomMsg_Name
	//	*RoomMsg_Msg
	RoomMsgValues isRoomMsg_RoomMsgValues `protobuf_oneof:"room_msg_values"`
}

func (m *RoomMsg) Reset()                    { *m = RoomMsg{} }
func (m *RoomMsg) String() string            { return proto.CompactTextString(m) }
func (*RoomMsg) ProtoMessage()               {}
func (*RoomMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isRoomMsg_RoomMsgValues interface {
	isRoomMsg_RoomMsgValues()
}

type RoomMsg_Name struct {
	Name string `protobuf:"bytes,3,opt,name=name,oneof"`
}
type RoomMsg_Msg struct {
	Msg string `protobuf:"bytes,4,opt,name=msg,oneof"`
}

func (*RoomMsg_Name) isRoomMsg_RoomMsgValues() {}
func (*RoomMsg_Msg) isRoomMsg_RoomMsgValues()  {}

func (m *RoomMsg) GetRoomMsgValues() isRoomMsg_RoomMsgValues {
	if m != nil {
		return m.RoomMsgValues
	}
	return nil
}

func (m *RoomMsg) GetMsgType() RoomMsg_RoomMsgType {
	if m != nil {
		return m.MsgType
	}
	return RoomMsg_USER_JOIN
}

func (m *RoomMsg) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RoomMsg) GetName() string {
	if x, ok := m.GetRoomMsgValues().(*RoomMsg_Name); ok {
		return x.Name
	}
	return ""
}

func (m *RoomMsg) GetMsg() string {
	if x, ok := m.GetRoomMsgValues().(*RoomMsg_Msg); ok {
		return x.Msg
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RoomMsg) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RoomMsg_OneofMarshaler, _RoomMsg_OneofUnmarshaler, _RoomMsg_OneofSizer, []interface{}{
		(*RoomMsg_Name)(nil),
		(*RoomMsg_Msg)(nil),
	}
}

func _RoomMsg_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RoomMsg)
	// room_msg_values
	switch x := m.RoomMsgValues.(type) {
	case *RoomMsg_Name:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Name)
	case *RoomMsg_Msg:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Msg)
	case nil:
	default:
		return fmt.Errorf("RoomMsg.RoomMsgValues has unexpected type %T", x)
	}
	return nil
}

func _RoomMsg_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RoomMsg)
	switch tag {
	case 3: // room_msg_values.name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.RoomMsgValues = &RoomMsg_Name{x}
		return true, err
	case 4: // room_msg_values.msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.RoomMsgValues = &RoomMsg_Msg{x}
		return true, err
	default:
		return false, nil
	}
}

func _RoomMsg_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RoomMsg)
	// room_msg_values
	switch x := m.RoomMsgValues.(type) {
	case *RoomMsg_Name:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Name)))
		n += len(x.Name)
	case *RoomMsg_Msg:
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Msg)))
		n += len(x.Msg)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "UserRequest")
	proto.RegisterType((*ChatMsg)(nil), "ChatMsg")
	proto.RegisterType((*RoomMsg)(nil), "RoomMsg")
	proto.RegisterEnum("UserRequest_UserRequestType", UserRequest_UserRequestType_name, UserRequest_UserRequestType_value)
	proto.RegisterEnum("RoomMsg_RoomMsgType", RoomMsg_RoomMsgType_name, RoomMsg_RoomMsgType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Chat service

type ChatClient interface {
	Chat(ctx context.Context, opts ...grpc.CallOption) (Chat_ChatClient, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Chat(ctx context.Context, opts ...grpc.CallOption) (Chat_ChatClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Chat_serviceDesc.Streams[0], c.cc, "/Chat/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatChatClient{stream}
	return x, nil
}

type Chat_ChatClient interface {
	Send(*UserRequest) error
	Recv() (*RoomMsg, error)
	grpc.ClientStream
}

type chatChatClient struct {
	grpc.ClientStream
}

func (x *chatChatClient) Send(m *UserRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatChatClient) Recv() (*RoomMsg, error) {
	m := new(RoomMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Chat service

type ChatServer interface {
	Chat(Chat_ChatServer) error
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).Chat(&chatChatServer{stream})
}

type Chat_ChatServer interface {
	Send(*RoomMsg) error
	Recv() (*UserRequest, error)
	grpc.ServerStream
}

type chatChatServer struct {
	grpc.ServerStream
}

func (x *chatChatServer) Send(m *RoomMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatChatServer) Recv() (*UserRequest, error) {
	m := new(UserRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Chat",
	HandlerType: (*ChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _Chat_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x51, 0xd1, 0x4e, 0xc2, 0x30,
	0x14, 0xa5, 0x8c, 0x30, 0xb8, 0x28, 0xcc, 0x8a, 0x91, 0x18, 0x1f, 0xc8, 0xe2, 0x03, 0x0f, 0x06,
	0x09, 0x9a, 0xf8, 0xe0, 0x13, 0x10, 0x22, 0x18, 0x95, 0xa4, 0x82, 0xaf, 0xcb, 0x94, 0x06, 0x4c,
	0xac, 0xdd, 0xda, 0xcd, 0x84, 0x6f, 0xf3, 0x1b, 0xfc, 0x27, 0xd3, 0x76, 0x23, 0x9d, 0x4f, 0x3d,
	0xe7, 0xb6, 0xbd, 0xe7, 0x9e, 0x73, 0x01, 0xde, 0xb7, 0x61, 0xd2, 0x8f, 0x04, 0x4f, 0xb8, 0xff,
	0x83, 0xa0, 0xb1, 0x92, 0x54, 0x10, 0x1a, 0xa7, 0x54, 0x26, 0xf8, 0x16, 0x6a, 0x82, 0xc6, 0x41,
	0xb2, 0x8b, 0x68, 0x07, 0x75, 0x51, 0xaf, 0x39, 0x3c, 0xef, 0x5b, 0xf7, 0x36, 0x5e, 0xee, 0x22,
	0x4a, 0x5c, 0x41, 0x63, 0x05, 0x70, 0x1b, 0x2a, 0x5f, 0x21, 0xa3, 0x9d, 0x72, 0x17, 0xf5, 0xea,
	0xb3, 0x12, 0xd1, 0x4c, 0x55, 0x95, 0x58, 0xc7, 0xc9, 0xab, 0x8a, 0xf9, 0x03, 0x68, 0xfd, 0xeb,
	0x83, 0x9b, 0x00, 0xab, 0x97, 0x29, 0x09, 0x1e, 0x17, 0xf7, 0xf3, 0x67, 0xaf, 0x84, 0x0f, 0xa1,
	0xae, 0xf9, 0x64, 0x36, 0x5a, 0x7a, 0x68, 0x7c, 0x02, 0xc7, 0xa9, 0xa4, 0x22, 0x10, 0xe6, 0x4b,
	0xf0, 0x1d, 0x7e, 0xa6, 0x54, 0xfa, 0x37, 0xe0, 0x4e, 0xb6, 0x61, 0xf2, 0x24, 0x37, 0xf8, 0x14,
	0x5c, 0xfd, 0xe2, 0x63, 0xad, 0xe7, 0x76, 0x48, 0x55, 0xd1, 0xf9, 0x1a, 0x7b, 0xe0, 0x30, 0xb9,
	0x31, 0x73, 0x11, 0x05, 0xfd, 0x5f, 0x04, 0x2e, 0xe1, 0x9c, 0xa9, 0x6f, 0x57, 0x50, 0x63, 0x72,
	0x63, 0xfb, 0x6d, 0xf7, 0xb3, 0xbb, 0xfc, 0x34, 0x3e, 0x99, 0x01, 0xb6, 0x4e, 0xb9, 0xa0, 0x93,
	0x07, 0xe0, 0x14, 0x02, 0xc0, 0x46, 0xbd, 0x92, 0x15, 0xb5, 0xfe, 0x1d, 0x34, 0xac, 0xd6, 0x7b,
	0xab, 0x0f, 0x0b, 0xed, 0x7c, 0x9f, 0xc4, 0x74, 0xf4, 0x3a, 0xf5, 0x50, 0x31, 0x89, 0xf2, 0xf8,
	0x08, 0x5a, 0x82, 0x73, 0x16, 0xa8, 0xa9, 0x4d, 0x0a, 0xc3, 0x4b, 0xa8, 0xa8, 0x14, 0xf0, 0x45,
	0x76, 0x1e, 0xd8, 0x5b, 0x3a, 0xab, 0xe5, 0x3e, 0xfc, 0x52, 0x0f, 0x0d, 0xd0, 0x5b, 0x55, 0x2f,
	0xfe, 0xfa, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x53, 0x22, 0x41, 0x06, 0x02, 0x00, 0x00,
}
